name: Run Email Script

on:
  schedule:
    - cron: '* * * * *'  # Exécuter toutes les minutes

jobs:
  run-script:
    runs-on: ubuntu-latest  # Utilise une machine virtuelle Ubuntu pour exécuter le script
    
    steps:
      # Étape 1: Check-out du code depuis le repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2: Installer Python et les dépendances
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Utilisez la version de Python que vous préférez

      # Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 3: Exécuter le script Python
      - name: Run the email script
        run: |
          python script.py
        env:
          # Vous pouvez utiliser les GitHub secrets ici pour sécuriser vos informations sensibles
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          
